#!/bin/bash

set -e

CMD="$*"

if [ -z "$CMD" ]; then
 echo "You must provide a command, for example: ./scripts/ci npm run test:ci"
fi

echo "Building a development Docker image"
docker build -t react-starter-ci .

echo "Running ${CMD} in react-starter-ci container"
docker run --rm \
    -v /home/node/node_modules \
    -v "$(pwd)":/home/node \
    react-starter-ci \
    $CMD
