#!/bin/bash

set -e

echo "Building a development Docker image"
docker build -t react-starter-local-dev .

[[ $# -eq 0 ]] && cmd="bash" || cmd="$@"
echo "Running ${cmd} in the development container"
docker run --rm -it \
    -v /home/node/node_modules \
    -v "$(pwd)":/home/node \
    -p 3000:3000 \
    react-starter-local-dev \
    $cmd
