name: "Actions to run when code is pushed to master"

on:
  pull_request:
    branches:
      - main

jobs:
  run_code_quality_and_tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2

      - name: "Run the linter"
        run: ./scripts/ci npm run lint

      - name: "Run tests"
        run: ./scripts/ci npm run test:ci
